name: hd2mm
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0-preview2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  bitsdojo_window: ^0.1.6
  provider: ^6.1.4
  path: ^1.9.1
  file_picker: ^10.0.0
  json_annotation: ^4.9.0
  http: ^1.3.0
  logging: ^1.3.0
  async: ^2.12.0
  ffi: ^2.1.4
  uuid: ^4.5.1
  archive: ^4.0.7
  desktop_drop: ^0.6.0
  idle_detector_wrapper: ^1.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  json5: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  package_rename: ^1.9.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Blockletter
      fonts:
        - asset: assets/fonts/Blockletter.otf
    - family: FS Sinclair
      fonts:
        - asset: assets/fonts/FS Sinclair Regular.otf
          weight: 200
        - asset: assets/fonts/FS Sinclair Medium.otf
          weight: 400
        - asset: assets/fonts/FS Sinclair Bold.otf
          weight: 700

package_rename_config:
  linux:
    app_name: Helldivers 2 Mod Manager
    package_name: com.teutinsa.hd2mm
    exe_name: hd2mm
  windows:
    app_name: Helldivers 2 Mod Manager
    organization: teutinsa
    copyright_notice: Copyright © 2025 teutinsa. All rights reserved.
    exe_name: Helldivers2ModManager